config/routes.rb
Rails.application.routes.draw do
  resources :evacuation_essentials
  resources :relief_goods
  resources :families
  resources :disasters
  resources :evac_centers
  resources :base_records
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to:"main#index"
  get "/error",to:"main#error"
  get "/evac_essentials_form/:evac_id/:profile_id", to: "evac_centers#evac_essentials_form"
  get "/evac_facilities_form/:evac_id/:profile_id", to: "evac_centers#evac_facilities_form"
  get "/evac_centers/show/archives",to:"evac_centers#archives"
  get "/log_relief_form", to: "main#log_relief_form"
  get "/login", to: "main#login"
  get "/register", to: "main#register"
  get "/requestcreate", to: "main#reqCreate"
  get "/logout",to:"main#logout"
  get "/account", to:"main#account"
  get "/requests",to:"volunteer#volunteer_requests"
  get "/families", to: "main#evac_families"
  get "/dashboard",to:"main#index"
  get "/new_user/:id",to:"volunteer#first_login"
  get "/volunteers",to:"volunteer#index"
  get "/download/:id/:img_id/:counter",to:"volunteer#download"
  get "/camp_manager/new",to:"main#new_camp_manager"
  get "/camp_managers",to:"volunteer#camp_managers"
  get "/admins",to:"volunteer#admins"
  get "/forgot_password",to:"main#forgot_password"
  get "/change_password/:id/:session_id",to:"main#change_password"

  post "/search_account",to:"main#search_account"
  post "/send_change_password_request", to:"main#send_change_password_request"
  post "/change_password/request",to:"main#change_pass_proceed"

  # base tables
  post "/disasters/search",to:"disasters#search"
  post "/families/search",to:"families#search"
  post "/relief_goods/search",to:"relief_goods#search"
  post "/evacuation_essentials/search",to:"evacuation_essentials#search"
  post "/add_facility",to:"evac_centers#add_facility"
  post "/add_item",to:"evac_centers#add_item"

  ## GENERATION OF REPORT

  get "evac_centers/:evac_center/:disaster_id/generate", to: "generate_report#generate"
  get "evac_centers/:evac_center/:disaster_id/view_report", to: "generate_report#viewSpecificReport"
  get "disasters/:disaster_id/generate", to: "generate_report#generate_all"
  get "disasters/:disaster_id/view_report", to: "generate_report#viewGeneralReport"
  ## LOGGING

  get "evac_centers/:id/log/:disaster_id", to: "log_family#logging"
  get "evac_centers/:evac_id/:disaster_id/evacuated", to: "log_family#evacuatedView"
  post "evac_centers/:evac_id/:disaster_id/out/:member_id", to: "log_family#evacueeOut"
  post "evac_centers/:evac_id/:disaster_id/released/:member_id", to: "log_family#evacueeReleased"
  post "/evac_centers/:id/archive",to:"evac_centers#archive_center"
  post "/evac_centers/:id/unarchive",to:"evac_centers#unarchive_center"
  post "/view_evacuated_family", to: "log_family#view_evacuated_family"
  post "log/search",to:"log_family#search"
  post "/log/:member_id/:evac_id/:disaster_id", to: "log_family#evacuate"
  post "/log/all/:family_id",to:"log_family#evacuate_all"
  post "/view_disaster_evacuation",to: "evac_centers#view_disaster_evacuation", action: :view_dis
  post "/evacuated/sort_by",to:"log_family#sort_by"

  post "/login/proceed",to:"main#login_proceed"
  post "/send_request",to:"main#send_request_proceed"
  post "/register/camp_manager", to: "main#create_campmanager"
  post "/requests/:id",to:"volunteer#display_request"
  post "/volunteer/:id",to:"volunteer#display_volunteer"
  post "/approve_request/:id",to:"volunteer#approve_request"
  post "/reject_request/:id",to:"volunteer#reject_request"
  post "/change_password",to:"volunteer#change_password"
  post "/add_volunteer",to:"evac_centers#add_volunteer"
  post "/add_campmanager",to:"evac_centers#add_campmanager"
  post "/evac_centers/:id/display_year_profile",to:"evac_centers#display_yearly_profile"
  post "/users/search",to:"volunteer#search"
  post "/evac_centers/search",to:"evac_centers#search"
  post "/families/add_member",to:"families#add_member"
  post "/edit/member/:id" , to:"families#edit_member"
  post "/families/edit_member", to:"families#update_member"
  post  "/remove_campmanager/:id",to:"evac_centers#remove_campmanager"
  post "/add_new_profile/:id",to:"evac_centers#add_profile"


  #RELIEF GOOD ALLOCATION
  get "/relief_good/requests",to:"relief_allocation#relief_request"
  get "/relief_good/accepted_requests",to:"relief_allocation#accepted_request"
  get "/relief_good/rejected_requests",to:"relief_allocation#rejected_request"
  get "/dispatch/request/:id",to: "relief_allocation#allocation"
  get "/relief_good/dispatched_requests",to:"relief_allocation#dispatched_request"
  get "/relief_allocation/:evac_id/:disaster_id", to: "relief_allocation#your_request"
  get "/relief_allocation/configuration/:evac_id/:disaster_id", to: "relief_allocation#configuration"
  get "/relief_allocation/storage/:evac_id/:disaster_id",to: "relief_allocation#storage"
  get "/evac_centers/distributed_rg/:evac_id/:disaster_id", to:"relief_allocation#distributed_rg"
  get "/evac_centers/non_distributed_rg/:evac_id/:disaster_id", to:"relief_allocation#non_distributed_rg"
  get "/view/evacuee/members/:id/:method", to:"relief_allocation#view_evac_members"

  post "/send/relief/:evac_id/:disaster_id",to:"relief_allocation#send_request"
  post "/view/request/:id",to:"relief_allocation#view_request"
  post "/approve/request/:id",to:"relief_allocation#approve_request"
  post "/reject/request/:id",to:"relief_allocation#reject_request"
  post "/revert/request/:id",to:"relief_allocation#revert_request"
  post "/allocate_rg",to:"relief_allocation#allocate_rg"
  post "/edit_rg/:rg_id/:request_id",to:"relief_allocation#edit_rg"
  post "/dispatch/request/:id",to: "relief_allocation#dispatch_request"
  post "/mark_received/request/:id",to:"relief_allocation#receive_request"
  post "/sort_by", to: "relief_allocation#sort_by"
  post "/sort_by/type", to: "relief_allocation#sort_by_type"
  post "/sort_by/search", to: "relief_allocation#sort_by_search"
  post "/show/configurations", to:"relief_allocation#show_configurations"
  post "/save/configuration/:id",to:"relief_allocation#save_configuration"
  post "/distribute/relief_goods/:id", to:"relief_allocation#distribute_goods"
  post "/view/allocated_rgs", to:"relief_allocation#view_allocated_rgs"
  post "/search/evacuees", to:"relief_allocation#search_evacuees"


  delete "/remove_volunteer/:id",to:"evac_centers#remove_volunteer"
  delete "/evac_centers/:id/destroy",to:"evac_centers#destroy"
  delete "/family_member/:id/destroy",to:"families#destroy_member"
  delete "/assigned_essential/:id",to:"evac_centers#destroy_essential"

end

app/models/evacuation_essential.rb
class EvacuationEssential < ApplicationRecord
    validates :name, :ess_type, presence:true
end

app/controllers/evacuation_essentials_controller.rb
class EvacuationEssentialsController < ApplicationController
  before_action :set_evacuation_essential, only: %i[ show edit update destroy ]
  before_action :add_index_breadcrumb, only: [:show, :new, :edit]
  before_action :is_logged_in

  def search
    search_type = params[:search_type]
    if search_type == "TYPE"
      search_type = "ess_type"
    else
      search_type = "name"
    end
    @evacuation_essentials = EvacuationEssential.where("#{search_type} LIKE ? ", "#{params[:search_value]}%").order(:name)
    respond_to do |format|
      if @evacuation_essentials.length > 0
          format.turbo_stream{render turbo_stream: turbo_stream.update("evacuation_essentials",partial: "search_results", locals:{evacuation_essentials:@evacuation_essentials })}
      elsif @evacuation_essentials.length <= 0
          format.turbo_stream{render turbo_stream: turbo_stream.update("evacuation_essentials","<h2 style = 'text-align:center'>No Record/s found.</h2>")}
      end
    end
  end
  # GET /evacuation_essentials or /evacuation_essentials.json
  def index
    add_breadcrumb('Evacuation Essentials')
    @evacuation_essentials = EvacuationEssential.all

    @page = params.fetch(:page, 0).to_i
    if  @page < 0
        @page = 0
    end
    @evacuation_essentials_count = @evacuation_essentials.length
    @evacuation_essentials_per_page = 5
    @evacuation_essentials = EvacuationEssential.offset(@page * @evacuation_essentials_per_page).limit(@evacuation_essentials_per_page).order(:name)
  end

  # GET /evacuation_essentials/1 or /evacuation_essentials/1.json
  def show
  end

  # GET /evacuation_essentials/new
  def new
    @evacuation_essential = EvacuationEssential.new
    add_breadcrumb('Add Essential')
  end

  # GET /evacuation_essentials/1/edit
  def edit
    add_breadcrumb(@evacuation_essential.name.titleize)
  end

  # POST /evacuation_essentials or /evacuation_essentials.json
  def create
    @evacuation_essential = EvacuationEssential.new(evacuation_essential_params)
    @evacuation_essential.name = @evacuation_essential.name.upcase
    respond_to do |format|
      if @evacuation_essential.save
        format.html { redirect_to "/evacuation_essentials", notice: "Evacuation essential was successfully created." }
        format.json { render :show, status: :created, location: @evacuation_essential }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @evacuation_essential.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evacuation_essentials/1 or /evacuation_essentials/1.json
  def update

    respond_to do |format|
      params[:evacuation_essential][:name] = params[:evacuation_essential][:name].upcase
      if @evacuation_essential.update(evacuation_essential_params)
        format.html { redirect_to "/evacuation_essentials", notice: "Evacuation essential was successfully updated." }
        format.json { render :show, status: :ok, location: @evacuation_essential }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @evacuation_essential.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evacuation_essentials/1 or /evacuation_essentials/1.json
  def destroy
    @evacuation_essential.destroy

    respond_to do |format|
      format.html { redirect_to evacuation_essentials_url, notice: "Evacuation essential was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def add_index_breadcrumb
    add_breadcrumb('Evacuation Essentials', evacuation_essentials_path)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evacuation_essential
      @evacuation_essential = EvacuationEssential.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def evacuation_essential_params
      params.require(:evacuation_essential).permit(:name, :description, :ess_type)
    end
end

app/helpers/evacuation_essentials_helper.rb
module EvacuationEssentialsHelper
end

app/views/evacuation_essentials/_evacuation_essential.html.erb
<div id="<%= dom_id evacuation_essential %>">
  <p>
    <strong>Name:</strong>
    <%= evacuation_essential.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= evacuation_essential.description %>
  </p>

  <p>
    <strong>Ess type:</strong>
    <%= evacuation_essential.ess_type %>
  </p>

</div>

app/views/evacuation_essentials/_form.html.erb
<%= form_with(model: evacuation_essential) do |form| %>
  <% invalid_name = evacuation_essential.errors.include?(:name) %>
  <% invalid_type = evacuation_essential.errors.include?(:ess_type) %>
  <div class="card shadow p-4 m-1">
    <h2 class="my-3 oswald fw-bold" style="border-bottom: 2px solid black;" >EVACUATION ESSENTIALS AND FACILITIES INFORMATION</h2>
    <div class="form-group">
      <%= form.label :name, class: "h5 oswald fw text-uppercase" do %>
        Name: 
      <% end %>
      <%= form.text_field :name, class:"form-control #{'is-invalid' if invalid_name}", placeholder: "Name"%>
      <% if invalid_name %>
        <div class="invalid-feedback d-block">
          <% evacuation_essential.errors[:name].each do |error_message| %>
            <%= error_message %>.
          <% end %>
        </div>
      <% end %>
    </div>
    <br>
    <div class="form-group">
      <%= form.label :type, class: "h5 oswald fw text-uppercase" do %>
        Essential Type: 
      <% end %>
      <% if evacuation_essential.ess_type == nil %>
        <%= form.select :ess_type, options_for_select(["FACILITY", "ESSENTIAL"]), {:prompt => "Select Type"}, {class: "form-control #{'is-invalid' if invalid_type}"} %>
      <% else %>
        <%= form.select :ess_type, options_for_select(["FACILITY", "ESSENTIAL"],:selected => evacuation_essential.ess_type.to_s ), {:prompt => "Select Type"}, {class: "form-control #{'is-invalid' if invalid_type}"} %>
      <%  end %>
      <% if invalid_type %>
        <div class="invalid-feedback d-block">
          <% evacuation_essential.errors[:ess_type].each do |error_message| %>
            <%= error_message %>.
          <% end %>
        </div>
      <% end %>
    </div>
    <br>
    <div class="form-group">
      <%= form.label :description, class: "h5 oswald fw text-uppercase" do %>
        Description: 
      <% end %>
      <%= form.text_area :description, class:"form-control", placeholder: "Description"%>
    </div>
    <div class="row justify-content-end mx-1 mt-3">
      <%= form.submit "Submit", class:"col-auto btn btn-primary bg-navy oswald px-3 text-decoration-none"%>
    </div>
  </div>
<% end %>

app/views/evacuation_essentials/_search_results.html.erb
<table class="table table-striped table-hover border rounded">
  <thead>
    <tr>
      <th class="col">Name</th>
      <th class="col">Description</th>
      <th class="col">Type</th>
      <th class="col text-center">Actions</th>
    </tr>
  </thead>
  <tbody class="table-group-divider">
    <% evacuation_essentials.each do |es|%>
      <tr>
        <td><b><%= es.name%></b></td>
        <td><%= es.description %></td>
        <td><%= es.ess_type%></td>
        <td>
          <%= link_to "/evacuation_essentials/#{es.id}/edit", class: "btn btn-outline-dark form-control" do %>
            <i class="fa-regular fa-pen-to-square"></i>&nbsp;Edit
          <% end %>
        </tr>
      </td>
    <% end %>
  </tbody>
</table>

app/views/evacuation_essentials/edit.html.erb
<div class="row m-0">
  <div class="col-md-11 m-5 text-xs-center  mt-5">
    <div class="card" >
      <div class="card-body" >
        <div class="card-deck">
          <div id = "form_area">
            <%= render partial:"form", locals:{evacuation_essential:@evacuation_essential}%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/evacuation_essentials/index.html.erb
<div class="row m-0 mt-5">
  <div class="col-md-11 m-5 text-xs-center  mt-5">
    <div class="card" >
      <div class="card-body" >
        <div class="card-deck">
          <div class="card shadow p-4">
            <div class = "row">
              <div class = "col-md-8">
                <h1 class="oswald fw">EVACUATION ESSENTIALS</h1>
              </div>
              <div class = "col-md-4">
                <a href = "/evacuation_essentials/new" ><button style = "margin-top:5px;" class = "btn btn-primary bg-navy oswald fw-bold form-control"><i class="fa-solid fa-plus"></i> Add New Evacuation Essential</button></a>
              </div>
            </div>
            <%= form_with url: "/evacuation_essentials/search", method: :post do |form| %>
              <label for = "search_criteria"><strong>Search Criteria:</strong></label>
              <div class="input-group mb-3">
                <%= form.select :search_type, options_for_select(["NAME","TYPE"]),{},{class:"form-control"}%>
                <%= form.search_field :search_value , class: "form-control", placeholder: "Search a data here", oninput: "this.form.requestSubmit()" %>
              </div>
            <% end %>
            <div id = "evacuation_essentials">
              <%= render partial: "search_results",locals:{evacuation_essentials:@evacuation_essentials}%>
            </div>
            <% if @evacuation_essentials_count > 5 %>
              <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-left">
                  <li class="page-item ">
                    <% if @page  > 0 %>
                      <%= link_to "Previous Page", "/evacuation_essentials?page=#{@page-1}", class:"page-link"%>
                    <% end %>
                  </li>
                  <li class="page-item">
                    <%= link_to "Next Page","/evacuation_essentials?page=#{@page + 1}", class:"page-link"%>
                  </li>
                </ul>
              </nav>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/evacuation_essentials/new.html.erb
<div class="row m-0">
  <div class="col-md-11 m-5 text-xs-center  mt-5">
    <div class="card" >
      <div class="card-body" >
        <div class="card-deck">
          <div id = "form_area">
            <%= render partial:"form", locals:{evacuation_essential:@evacuation_essential}%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/evacuation_essentials/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @evacuation_essential %>

<div>
  <%= link_to "Edit this evacuation essential", edit_evacuation_essential_path(@evacuation_essential) %> |
  <%= link_to "Back to evacuation essentials", evacuation_essentials_path %>

  <%= button_to "Destroy this evacuation essential", @evacuation_essential, method: :delete %>
</div>