config/routes.rb
Rails.application.routes.draw do
  resources :evacuation_essentials
  resources :relief_goods
  resources :families
  resources :disasters
  resources :evac_centers
  resources :base_records
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to:"main#index"
  get "/error",to:"main#error"
  get "/evac_essentials_form/:evac_id/:profile_id", to: "evac_centers#evac_essentials_form"
  get "/evac_facilities_form/:evac_id/:profile_id", to: "evac_centers#evac_facilities_form"
  get "/evac_centers/show/archives",to:"evac_centers#archives"
  get "/log_relief_form", to: "main#log_relief_form"
  get "/login", to: "main#login"
  get "/register", to: "main#register"
  get "/requestcreate", to: "main#reqCreate"
  get "/logout",to:"main#logout"
  get "/account", to:"main#account"
  get "/requests",to:"volunteer#volunteer_requests"
  get "/families", to: "main#evac_families"
  get "/dashboard",to:"main#index"
  get "/new_user/:id",to:"volunteer#first_login"
  get "/volunteers",to:"volunteer#index"
  get "/download/:id/:img_id/:counter",to:"volunteer#download"
  get "/camp_manager/new",to:"main#new_camp_manager"
  get "/camp_managers",to:"volunteer#camp_managers"
  get "/admins",to:"volunteer#admins"
  get "/forgot_password",to:"main#forgot_password"
  get "/change_password/:id/:session_id",to:"main#change_password"

  post "/search_account",to:"main#search_account"
  post "/send_change_password_request", to:"main#send_change_password_request"
  post "/change_password/request",to:"main#change_pass_proceed"

  # base tables
  post "/disasters/search",to:"disasters#search"
  post "/families/search",to:"families#search"
  post "/relief_goods/search",to:"relief_goods#search"
  post "/evacuation_essentials/search",to:"evacuation_essentials#search"
  post "/add_facility",to:"evac_centers#add_facility"
  post "/add_item",to:"evac_centers#add_item"

  ## GENERATION OF REPORT

  get "evac_centers/:evac_center/:disaster_id/generate", to: "generate_report#generate"
  get "evac_centers/:evac_center/:disaster_id/view_report", to: "generate_report#viewSpecificReport"
  get "disasters/:disaster_id/generate", to: "generate_report#generate_all"
  get "disasters/:disaster_id/view_report", to: "generate_report#viewGeneralReport"
  ## LOGGING

  get "evac_centers/:id/log/:disaster_id", to: "log_family#logging"
  get "evac_centers/:evac_id/:disaster_id/evacuated", to: "log_family#evacuatedView"
  post "evac_centers/:evac_id/:disaster_id/out/:member_id", to: "log_family#evacueeOut"
  post "evac_centers/:evac_id/:disaster_id/released/:member_id", to: "log_family#evacueeReleased"
  post "/evac_centers/:id/archive",to:"evac_centers#archive_center"
  post "/evac_centers/:id/unarchive",to:"evac_centers#unarchive_center"
  post "/view_evacuated_family", to: "log_family#view_evacuated_family"
  post "log/search",to:"log_family#search"
  post "/log/:member_id/:evac_id/:disaster_id", to: "log_family#evacuate"
  post "/log/all/:family_id",to:"log_family#evacuate_all"
  post "/view_disaster_evacuation",to: "evac_centers#view_disaster_evacuation", action: :view_dis
  post "/evacuated/sort_by",to:"log_family#sort_by"

  post "/login/proceed",to:"main#login_proceed"
  post "/send_request",to:"main#send_request_proceed"
  post "/register/camp_manager", to: "main#create_campmanager"
  post "/requests/:id",to:"volunteer#display_request"
  post "/volunteer/:id",to:"volunteer#display_volunteer"
  post "/approve_request/:id",to:"volunteer#approve_request"
  post "/reject_request/:id",to:"volunteer#reject_request"
  post "/change_password",to:"volunteer#change_password"
  post "/add_volunteer",to:"evac_centers#add_volunteer"
  post "/add_campmanager",to:"evac_centers#add_campmanager"
  post "/evac_centers/:id/display_year_profile",to:"evac_centers#display_yearly_profile"
  post "/users/search",to:"volunteer#search"
  post "/evac_centers/search",to:"evac_centers#search"
  post "/families/add_member",to:"families#add_member"
  post "/edit/member/:id" , to:"families#edit_member"
  post "/families/edit_member", to:"families#update_member"
  post  "/remove_campmanager/:id",to:"evac_centers#remove_campmanager"
  post "/add_new_profile/:id",to:"evac_centers#add_profile"


  #RELIEF GOOD ALLOCATION
  get "/relief_good/requests",to:"relief_allocation#relief_request"
  get "/relief_good/accepted_requests",to:"relief_allocation#accepted_request"
  get "/relief_good/rejected_requests",to:"relief_allocation#rejected_request"
  get "/dispatch/request/:id",to: "relief_allocation#allocation"
  get "/relief_good/dispatched_requests",to:"relief_allocation#dispatched_request"
  get "/relief_allocation/:evac_id/:disaster_id", to: "relief_allocation#your_request"
  get "/relief_allocation/configuration/:evac_id/:disaster_id", to: "relief_allocation#configuration"
  get "/relief_allocation/storage/:evac_id/:disaster_id",to: "relief_allocation#storage"
  get "/evac_centers/distributed_rg/:evac_id/:disaster_id", to:"relief_allocation#distributed_rg"
  get "/evac_centers/non_distributed_rg/:evac_id/:disaster_id", to:"relief_allocation#non_distributed_rg"
  get "/view/evacuee/members/:id/:method", to:"relief_allocation#view_evac_members"

  post "/send/relief/:evac_id/:disaster_id",to:"relief_allocation#send_request"
  post "/view/request/:id",to:"relief_allocation#view_request"
  post "/approve/request/:id",to:"relief_allocation#approve_request"
  post "/reject/request/:id",to:"relief_allocation#reject_request"
  post "/revert/request/:id",to:"relief_allocation#revert_request"
  post "/allocate_rg",to:"relief_allocation#allocate_rg"
  post "/edit_rg/:rg_id/:request_id",to:"relief_allocation#edit_rg"
  post "/dispatch/request/:id",to: "relief_allocation#dispatch_request"
  post "/mark_received/request/:id",to:"relief_allocation#receive_request"
  post "/sort_by", to: "relief_allocation#sort_by"
  post "/sort_by/type", to: "relief_allocation#sort_by_type"
  post "/sort_by/search", to: "relief_allocation#sort_by_search"
  post "/show/configurations", to:"relief_allocation#show_configurations"
  post "/save/configuration/:id",to:"relief_allocation#save_configuration"
  post "/distribute/relief_goods/:id", to:"relief_allocation#distribute_goods"
  post "/view/allocated_rgs", to:"relief_allocation#view_allocated_rgs"
  post "/search/evacuees", to:"relief_allocation#search_evacuees"


  delete "/remove_volunteer/:id",to:"evac_centers#remove_volunteer"
  delete "/evac_centers/:id/destroy",to:"evac_centers#destroy"
  delete "/family_member/:id/destroy",to:"families#destroy_member"
  delete "/assigned_essential/:id",to:"evac_centers#destroy_essential"

end

app/models/disaster.rb
class Disaster < ApplicationRecord
    validates :name, :disaster_type, :date_of_occurence , presence:true
    has_many :evacuees
end
# rails g model Evacuee disaster_id:integer family_id:integer date_in:datetime date_out:datetime evac_id:integer

app/controllers/disasters_controller.rb
class DisastersController < ApplicationController
  before_action :set_disaster, only: %i[ show edit update destroy ]
  before_action :add_index_breadcrumb, only: [:new, :edit]
  before_action :is_logged_in
  before_action :checkValidUser

  # GET /disasters or /disasters.json
  def index
    add_breadcrumb('Disasters')
    @disasters = Disaster.all
    @page = params.fetch(:page, 0).to_i
    if  @page < 0
        @page = 0
    end
    @disasters_count = @disasters.length
    @disasters_count_per_page = 5
    @disasters = Disaster.offset(@page * @disasters_count_per_page).limit(@disasters_count_per_page).order(date_of_occurence: :desc)
  end

  def search
    search_type = params[:search_type]
    if search_type == "YEAR"
      search_type = "year"
    elsif search_type == "TYPE"
      search_type = "disaster_type"
    else
      search_type = "name"
    end
    search_value = params[:search_value].upcase
    @disasters = Disaster.where("#{search_type} LIKE ? ", "#{search_value}").order(:name)

    respond_to do |format|
      if @disasters.length > 0
          format.turbo_stream{render turbo_stream: turbo_stream.update("disasters",partial: "search_results", locals:{disasters:@disasters })}
      elsif @disasters.length <= 0
        @disasters = Disaster.all
          format.turbo_stream{render turbo_stream: turbo_stream.update("disasters",partial: "search_results", locals:{disasters:@disasters })}
      end
    end
  end


  # GET /disasters/1 or /disasters/1.json
  def show
  end

  # GET /disasters/new
  def new
    @disaster = Disaster.new
    add_breadcrumb('New Disaster')
  end

  # GET /disasters/1/edit
  def edit
    add_breadcrumb(@disaster.name.titleize)
  end

  # POST /disasters or /disasters.json
  def create
    @disaster = Disaster.new(disaster_params)
    @disaster.name = @disaster.name.upcase
    @disaster.year = @disaster.date_of_occurence.year
    respond_to do |format|
      if @disaster.save
        format.html { redirect_to "/disasters", notice: "Disaster was successfully created." }
        format.json { render :show, status: :created, location: @disaster }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @disaster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disasters/1 or /disasters/1.json
  def update
    respond_to do |format|
      params[:disaster][:name]  = params[:disaster][:name].upcase
      @disaster.year = @disaster.date_of_occurence.year
      if @disaster.update(disaster_params)
        format.html { redirect_to "/disasters", notice: "Disaster was successfully updated." }
        format.json { render :show, status: :ok, location: @disaster }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @disaster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disasters/1 or /disasters/1.json
  def destroy
    @disaster.destroy

    respond_to do |format|
      format.html { redirect_to disasters_url, notice: "Disaster was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def add_index_breadcrumb
    add_breadcrumb('Disasters', disasters_path)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_disaster
      @disaster = Disaster.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def disaster_params
      params.require(:disaster).permit(:name, :disaster_type, :year, :date_of_occurence)
    end
end

app/helpers/disasters_helper.rb
module DisastersHelper
end

app/views/disasters/_disaster.html.erb
<div id="<%= dom_id disaster %>">
  <p>
    <strong>Name:</strong>
    <%= disaster.name %>
  </p>

  <p>
    <strong>Disaster type:</strong>
    <%= disaster.disaster_type %>
  </p>

  <p>
    <strong>Year:</strong>
    <%= disaster.year %>
  </p>

</div>

app/views/disasters/_disaster_card.html.erb
<div class="col-md-3">
    <div id="disaster-card" class="card h-100 oswald border-0">
        <div class="card-header m-0">
            <h3 class="m-3 text-center poppins fw-bold">Typhoon Juan<i class="ms-3 fa-solid fa-hurricane"></i></h3>
        </div>
        <div class="card-body">
            <div class="row mb-1">
                <div class="col text-end">
                    <p>Date Occured</p>
                </div>
                <div class="col text-start">
                    <h5 class="fw-bold">2023, September 3</h6>
                </div>
            </div>
            <div class="row mb-1">
                <div class="col text-end">
                    <p>Disaster Type</p>
                </div>
                <div class="col text-start">
                    <h5 class="fw-bold">Typhoon</h6>
                </div>
            </div>
            <div class="row">
                <div class="col text-end">
                    <p>Sheltered Families</p>
                </div>
                <div class="col text-start">
                    <h3 class="fw-bold">23</h6>
                </div>
            </div>
            <div class="row">
                <div class="col text-end">
                    <p>Sheltered Individuals</p>
                </div>
                <div class="col text-start">
                    <h3 class="fw-bold">55</h6>
                </div>
            </div>

            <div id="disaster-desc" class="row p-1 pt-2 m-2 bg-white rounded">
                <p class="montserrat">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>
            </div>

            <div class="row mt-3">
                <div class="col"></div>
                    <div class="col">
                        <%= link_to "disasters/show/", class: "btn btn-secondary form-control" do %>
                            View <i class="fa-solid fa-eye"></i>
                        <% end %>
                    </div>
                <div class="col"></div>
            </div>
        </div>
    </div>
</div>

app/views/disasters/_form.html.erb
<%= form_with(model: disaster, local: true) do |form| %>
  <% invalid_name = disaster.errors.include?(:name) %>
  <% invalid_type = disaster.errors.include?(:disaster_type) %>
  <% invalid_year= disaster.errors.include?(:year) %>
  <div class="card shadow p-4 m-1">
    <h2 class="my-3 oswald fw-bold" >DISASTER INFORMATION</h2>
    <div class="form-group">
      <%= form.label :name, class: "h5 oswald fw text-uppercase" do %>
        Disaster Name: 
      <% end %>
      <%= form.text_field :name, class:"form-control #{'is-invalid' if invalid_name}", placeholder: "Disaster Name"%>
      <% if invalid_name %>
        <div class="invalid-feedback d-block">
          <% disaster.errors[:name].each do |error_message| %>
            <%= error_message %>.
          <% end %>
        </div>
      <% end %>
    </div>
    <br>
    <div class="form-group">
      <%= form.label :type, class: "h5 oswald fw text-uppercase" do %>
        Disaster Type: 
      <% end %>
      <% if disaster.disaster_type == nil %>
        <%= form.select :disaster_type, options_for_select(["Man-made", "Natural"]), {:prompt => "Select Type"}, {class: "form-control #{'is-invalid' if invalid_type}"} %>
      <% else %>
        <%= form.select :disaster_type, options_for_select(["Man-made", "Natural"],:selected => disaster.disaster_type.to_s ), {:prompt => "Select Type"}, {class: "form-control #{'is-invalid' if invalid_type}"} %>
      <%  end %>
      <% if invalid_type %>
        <div class="invalid-feedback d-block">
          <% disaster.errors[:disaster_type].each do |error_message| %>
            <%= error_message %>.
          <% end %>
        </div>
      <% end %>
    </div>
    <br>
    <div class="form-group">
      <%= form.label :date_of_occurence, class: "h5 oswald fw text-uppercase" do %>
        Date of Occurence: 
      <% end %>
      <%= form.date_field :date_of_occurence, class:"form-control #{'is-invalid' if invalid_year}", placeholder: "Date of Occurence", max: Date.today()%>
      <% if invalid_year %>
        <div class="invalid-feedback d-block">
          <% disaster.errors[:date_of_occurence].each do |error_message| %>
            <%= error_message %>.
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="row justify-content-end mx-1 mt-3">
      <%= form.submit "Submit", class:"col-auto btn btn-primary bg-navy oswald fw-bold mt-3 px-3 text-decoration-none"%>
    </div>
  </div>
<% end %>

app/views/disasters/_search_results.html.erb
<table class="table table-striped table-hover border rounded">
  <thead>
    <tr>
      <th class="col">Name</th>
      <th class="col">Type</th>
      <th class="col">Date of Occurence</th>
      <th class="col-md-4">Actions</th>
    </tr>
  </thead>
  <tbody class="table-group-divider">
    <% disasters.each do |disaster|%>
      <tr>
        <td><b><%= disaster.name%></b></td>
        <td><%= disaster.disaster_type %></td>
        <td><%= disaster.date_of_occurence%></td>
        <td class="row m-0 p-2">

            <div class="col-md-6">
              <%= link_to "/disasters/#{disaster.id}/edit", class: "btn btn-outline-dark form-control oswald fw-bold" do %>
                <i class="fa-regular fa-pen-to-square"></i>&nbsp;Edit
              <% end %>
            </div>
            <% if session[:user_type] == "ADMIN" || session[:user_type] == "SUPERUSER"%>
              <div class="col-md-6">
                <button  style="font-size: 20px" class="btn btn-dark bg-dgray dropdown-toggle oswald fw-bold form-control dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
                  DROMIC REPORT
                </button>
                
                <ul class="dropdown-menu oswald fw p-1 text-center" style="font-size:2em">
                  <p class="">Lists</p>
                  <li class="m-1"><a href="disasters/<%=disaster.id%>/generate.xlsx", class= "dropdown-item p-1 mt-1">DOWNLOAD as .xlsx <i class="fa-solid fa-table d-inline"></i></a></li>
                  <li class="m-1"><a href="disasters/<%=disaster.id%>/view_report", class= "dropdown-item p-1 mt-1">View Report <i class="fa-solid fa-eye"></i></a></li>
                </ul>
              </div>
            <%end%>
  
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/disasters/edit.html.erb
<div class="row m-0">
  <div class="col-md-11 m-5 text-xs-center  mt-5">
    <div class="card" >
      <div class="card-body" >
        <div class="card-deck">
          <div id = "form_area">
            <%= render partial: "form", locals:{disaster:@disaster}%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/disasters/index.html.erb
<div class="row m-0 mt-5">
  <div class="col-md-11 m-5 text-xs-center  mt-5">
    <div class="card" >
      <div class="card-body" >
        <div class="card-deck">
          <div class="card shadow p-4">
            <div class = "row">
              <div class = "col-md-8">
                <h1 class="oswald fw">DISASTERS</h1>
              </div>
              <div class = "col-md-4">
                <a href = "/disasters/new" ><button style = "margin-top:5px;" class = "btn btn-primary bg-navy oswald fw-bold form-control"><i class="fa-solid fa-plus"></i> Record new Disaster</button></a>
              </div>
            </div>
            <%= form_with url: "/disasters/search", method: :post do |form| %>
              <label for = "search_criteria"><strong>Search Criteria:</strong></label>
              <div class="input-group mb-3">
                <%= form.select :search_type, options_for_select(["NAME","TYPE","YEAR"]),{},{class:"form-control"}%>
                <%= form.search_field :search_value , class: "form-control", placeholder: "Search a data here", oninput: "this.form.requestSubmit()" %>
              </div>
            <% end %>
            <div id = "disasters">
              <%= render partial: "search_results",locals:{disasters:@disasters}%>
            </div>
            <% if @disasters_count > 5 %>
              <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-left">
                  <li class="page-item ">
                    <% if @page  > 0 %>
                      <%= link_to "Previous Page", "/disasters?page=#{@page-1}", class:"page-link"%>
                    <% end %>
                  </li>
                  <li class="page-item">
                    <%= link_to "Next Page","/disasters?page=#{@page + 1}", class:"page-link"%>
                  </li>
                </ul>
              </nav>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/disasters/new.html.erb
<div class="row m-0">
  <div class="col-md-11 m-5 text-xs-center">
    <div class="card" >
      <div class="card-body" >
        <div class="card-deck">
          <div id = "form_area">
            <%= render partial:"form", locals:{disaster:@disaster}%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/disasters/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @disaster %>

<div>
  <%= link_to "Edit this disaster", edit_disaster_path(@disaster) %> |
  <%= link_to "Back to disasters", disasters_path %>

  <%= button_to "Destroy this disaster", @disaster, method: :delete %>
</div>