config/routes.rb
Rails.application.routes.draw do
  resources :evacuation_essentials
  resources :relief_goods
  resources :families
  resources :disasters
  resources :evac_centers
  resources :base_records
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to:"main#index"
  get "/error",to:"main#error"
  get "/evac_essentials_form/:evac_id/:profile_id", to: "evac_centers#evac_essentials_form"
  get "/evac_facilities_form/:evac_id/:profile_id", to: "evac_centers#evac_facilities_form"
  get "/evac_centers/show/archives",to:"evac_centers#archives"
  get "/log_relief_form", to: "main#log_relief_form"
  get "/login", to: "main#login"
  get "/register", to: "main#register"
  get "/requestcreate", to: "main#reqCreate"
  get "/logout",to:"main#logout"
  get "/account", to:"main#account"
  get "/requests",to:"volunteer#volunteer_requests"
  get "/families", to: "main#evac_families"
  get "/dashboard",to:"main#index"
  get "/new_user/:id",to:"volunteer#first_login"
  get "/volunteers",to:"volunteer#index"
  get "/download/:id/:img_id/:counter",to:"volunteer#download"
  get "/camp_manager/new",to:"main#new_camp_manager"
  get "/camp_managers",to:"volunteer#camp_managers"
  get "/admins",to:"volunteer#admins"
  get "/forgot_password",to:"main#forgot_password"
  get "/change_password/:id/:session_id",to:"main#change_password"

  post "/search_account",to:"main#search_account"
  post "/send_change_password_request", to:"main#send_change_password_request"
  post "/change_password/request",to:"main#change_pass_proceed"

  # base tables
  post "/disasters/search",to:"disasters#search"
  post "/families/search",to:"families#search"
  post "/relief_goods/search",to:"relief_goods#search"
  post "/evacuation_essentials/search",to:"evacuation_essentials#search"
  post "/add_facility",to:"evac_centers#add_facility"
  post "/add_item",to:"evac_centers#add_item"

  ## GENERATION OF REPORT

  get "evac_centers/:evac_center/:disaster_id/generate", to: "generate_report#generate"
  get "evac_centers/:evac_center/:disaster_id/view_report", to: "generate_report#viewSpecificReport"
  get "disasters/:disaster_id/generate", to: "generate_report#generate_all"
  get "disasters/:disaster_id/view_report", to: "generate_report#viewGeneralReport"
  ## LOGGING

  get "evac_centers/:id/log/:disaster_id", to: "log_family#logging"
  get "evac_centers/:evac_id/:disaster_id/evacuated", to: "log_family#evacuatedView"
  post "evac_centers/:evac_id/:disaster_id/out/:member_id", to: "log_family#evacueeOut"
  post "evac_centers/:evac_id/:disaster_id/released/:member_id", to: "log_family#evacueeReleased"
  post "/evac_centers/:id/archive",to:"evac_centers#archive_center"
  post "/evac_centers/:id/unarchive",to:"evac_centers#unarchive_center"
  post "/view_evacuated_family", to: "log_family#view_evacuated_family"
  post "log/search",to:"log_family#search"
  post "/log/:member_id/:evac_id/:disaster_id", to: "log_family#evacuate"
  post "/log/all/:family_id",to:"log_family#evacuate_all"
  post "/view_disaster_evacuation",to: "evac_centers#view_disaster_evacuation", action: :view_dis
  post "/evacuated/sort_by",to:"log_family#sort_by"

  post "/login/proceed",to:"main#login_proceed"
  post "/send_request",to:"main#send_request_proceed"
  post "/register/camp_manager", to: "main#create_campmanager"
  post "/requests/:id",to:"volunteer#display_request"
  post "/volunteer/:id",to:"volunteer#display_volunteer"
  post "/approve_request/:id",to:"volunteer#approve_request"
  post "/reject_request/:id",to:"volunteer#reject_request"
  post "/change_password",to:"volunteer#change_password"
  post "/add_volunteer",to:"evac_centers#add_volunteer"
  post "/add_campmanager",to:"evac_centers#add_campmanager"
  post "/evac_centers/:id/display_year_profile",to:"evac_centers#display_yearly_profile"
  post "/users/search",to:"volunteer#search"
  post "/evac_centers/search",to:"evac_centers#search"
  post "/families/add_member",to:"families#add_member"
  post "/edit/member/:id" , to:"families#edit_member"
  post "/families/edit_member", to:"families#update_member"
  post  "/remove_campmanager/:id",to:"evac_centers#remove_campmanager"
  post "/add_new_profile/:id",to:"evac_centers#add_profile"


  #RELIEF GOOD ALLOCATION
  get "/relief_good/requests",to:"relief_allocation#relief_request"
  get "/relief_good/accepted_requests",to:"relief_allocation#accepted_request"
  get "/relief_good/rejected_requests",to:"relief_allocation#rejected_request"
  get "/dispatch/request/:id",to: "relief_allocation#allocation"
  get "/relief_good/dispatched_requests",to:"relief_allocation#dispatched_request"
  get "/relief_allocation/:evac_id/:disaster_id", to: "relief_allocation#your_request"
  get "/relief_allocation/configuration/:evac_id/:disaster_id", to: "relief_allocation#configuration"
  get "/relief_allocation/storage/:evac_id/:disaster_id",to: "relief_allocation#storage"
  get "/evac_centers/distributed_rg/:evac_id/:disaster_id", to:"relief_allocation#distributed_rg"
  get "/evac_centers/non_distributed_rg/:evac_id/:disaster_id", to:"relief_allocation#non_distributed_rg"
  get "/view/evacuee/members/:id/:method", to:"relief_allocation#view_evac_members"

  post "/send/relief/:evac_id/:disaster_id",to:"relief_allocation#send_request"
  post "/view/request/:id",to:"relief_allocation#view_request"
  post "/approve/request/:id",to:"relief_allocation#approve_request"
  post "/reject/request/:id",to:"relief_allocation#reject_request"
  post "/revert/request/:id",to:"relief_allocation#revert_request"
  post "/allocate_rg",to:"relief_allocation#allocate_rg"
  post "/edit_rg/:rg_id/:request_id",to:"relief_allocation#edit_rg"
  post "/dispatch/request/:id",to: "relief_allocation#dispatch_request"
  post "/mark_received/request/:id",to:"relief_allocation#receive_request"
  post "/sort_by", to: "relief_allocation#sort_by"
  post "/sort_by/type", to: "relief_allocation#sort_by_type"
  post "/sort_by/search", to: "relief_allocation#sort_by_search"
  post "/show/configurations", to:"relief_allocation#show_configurations"
  post "/save/configuration/:id",to:"relief_allocation#save_configuration"
  post "/distribute/relief_goods/:id", to:"relief_allocation#distribute_goods"
  post "/view/allocated_rgs", to:"relief_allocation#view_allocated_rgs"
  post "/search/evacuees", to:"relief_allocation#search_evacuees"


  delete "/remove_volunteer/:id",to:"evac_centers#remove_volunteer"
  delete "/evac_centers/:id/destroy",to:"evac_centers#destroy"
  delete "/family_member/:id/destroy",to:"families#destroy_member"
  delete "/assigned_essential/:id",to:"evac_centers#destroy_essential"

end

app/models/relief_good.rb
class ReliefGood < ApplicationRecord
    validates :name, :unit, :price,:eligibility,:category, presence: true
    validates :price, numericality:{greater_than_or_equal_to: 0}
end

app/controllers/relief_goods_controller.rb
class ReliefGoodsController < ApplicationController
  before_action :set_relief_good, only: %i[ show edit update destroy ]
  before_action :is_logged_in
  before_action :checkValidUser
  def search
    search_type = params[:search_type]
    if search_type == "UNIT"
      search_type = "unit"
    else
      search_type = "name"
    end
    @relief_goods = ReliefGood.where("#{search_type} LIKE ? ", "#{params[:search_value]}%").order(:name)
    respond_to do |format|
      if @relief_goods.length > 0
          format.turbo_stream{render turbo_stream: turbo_stream.update("relief_goods",partial: "search_results", locals:{relief_goods:@relief_goods })}
      elsif @relief_goods.length <= 0
        @relief_goods = ReliefGood.all
        format.turbo_stream{render turbo_stream: turbo_stream.update("relief_goods",partial: "search_results", locals:{relief_goods:@relief_goods })}
      end
    end
  end
  # GET /relief_goods or /relief_goods.json
  def index
    add_breadcrumb('Relief Goods')
    @relief_goods = ReliefGood.all
    @page = params.fetch(:page, 0).to_i
    if  @page < 0
        @page = 0
    end
    @relief_goods_count = @relief_goods.length
    @relief_goods_count_per_page = 10
    @relief_goods = ReliefGood.offset(@page * @relief_goods_count_per_page).limit(@relief_goods_count_per_page).order(:name)
  end

  # GET /relief_goods/1 or /relief_goods/1.json
  def show
  end

  # GET /relief_goods/new
  def new
    add_breadcrumb('Relief Goods', relief_goods_path)
    add_breadcrumb('Add Relief Goods')
    @relief_good = ReliefGood.new
  end

  # GET /relief_goods/1/edit
  def edit
    add_breadcrumb('Relief Goods', relief_goods_path)
    add_breadcrumb(@relief_good.name.titleize)
  end

  # POST /relief_goods or /relief_goods.json
  def create
    @relief_good = ReliefGood.new(relief_good_params)
    @relief_good.name = @relief_good.name.upcase

    respond_to do |format|
      if @relief_good.save
        format.html { redirect_to "/relief_goods", notice: "Relief good was successfully created." }
        format.json { render :show, status: :created, location: @relief_good }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @relief_good.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /relief_goods/1 or /relief_goods/1.json
  def update

    respond_to do |format|
      if @relief_good.update(relief_good_params)

        format.html { redirect_to  "/relief_goods", notice: "Relief good was successfully updated." }
        format.json { render :show, status: :ok, location: @relief_good }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @relief_good.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /relief_goods/1 or /relief_goods/1.json
  def destroy
    @relief_good.destroy

    respond_to do |format|
      format.html { redirect_to relief_goods_url, notice: "Relief good was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_relief_good
      @relief_good = ReliefGood.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def relief_good_params
      params.require(:relief_good).permit(:name, :is_food, :unit, :price, :eligibility, :category)
    end
end

app/helpers/relief_goods_helper.rb
module ReliefGoodsHelper
end

app/views/relief_goods/_form.html.erb
<%= form_with(model: relief_good) do |form| %>
  <% invalid_name = relief_good.errors.include?(:name) %>
  <% invalid_unit = relief_good.errors.include?(:unit) %>
  <% invalid_price = relief_good.errors.include?(:price) %>
  <% invalid_eligibility = relief_good.errors.include?(:eligibility) %>
  <% invalid_category = relief_good.errors.include?(:category) %>
  <div class="row">
    <div class="col">
      <div class="card shadow p-4 m-1">
        <h2 class="m-3 oswald fw-bold" >RELIEF INFORMATION</h2>
        <div class="form-group m-2 p-1">
          <%= form.label :name, class: "h5 oswald fw text-uppercase" do %>
            Name: 
          <% end %>
          <%= form.text_field :name, class:"form-control #{'is-invalid' if invalid_name}", placeholder: "Product Name"%>
          <% if invalid_name %>
            <div class="invalid-feedback d-block">
              <% relief_good.errors[:name].each do |error_message| %>
                <%= error_message %>.
              <% end %>
            </div>
          <% end %>
        </div>
        <div class="form-group m-2 p-1">
          <%= form.label :unit, class: "h5 oswald fw text-uppercase" do %>
            Unit of Measurement: 
          <% end %>
          <% if relief_good.unit == nil %>
            <%= form.select :unit, options_for_select(["Kilograms", "Pieces", "Meter"]), {:prompt => "Select Type"}, {class: "form-control #{'is-invalid' if invalid_unit}"} %>
          <% else %>
            <%= form.select :unit, options_for_select(["Kilograms", "Pieces", "Meter"],:selected => relief_good.unit.to_s ), {:prompt => "Select Type"}, {class: "form-control #{'is-invalid' if invalid_unit}"} %>
          <%  end %>
          <% if invalid_unit %>
            <div class="invalid-feedback d-block">
              <% relief_good.errors[:unit].each do |error_message| %>
                <%= error_message %>.
              <% end %>
            </div>
          <% end %>
        </div>
        <div class="form-group m-2 p-1">
          <%= form.label :price, class: "h5 oswald fw text-uppercase" do %>
            Cost Per Unit: 
          <% end %>
          <%= form.number_field :price, class:"form-control #{'is-invalid' if invalid_price}", placeholder: "Price Per Unit"%>
          <% if invalid_price %>
            <div class="invalid-feedback d-block">
              <% relief_good.errors[:price].each do |error_message| %>
                <%= error_message %>.
              <% end %>
            </div>
          <% end %>
        </div>
        <div class="row m-2 p-1">
          <div class="col-md-auto m-1">
            <%= form.label :is_food, "Is this a Food? (Toggle if its food)", class:"form-check-label h5 oswald fw m-0 p-0 text-uppercase w-100"%>
          </div>
          <div class="col-md-auto m-1">
            <div class="form-check form-switch d-inline" >
              <%= form.check_box :is_food, class:"form-check-input p-2 m-1"%>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card shadow p-4 m-1">
        <h2 class="m-3 oswald fw-bold" >RELIEF CONFIGURATION</h2>
        <div class="form-group m-2 p-1">
          <%= form.label :eligibility, class: "h5 oswald fw text-uppercase" do %>
            Product is for: 
          <% end %>
          <% if relief_good.eligibility == nil %>
            <%= form.select :eligibility, options_for_select(["MALE", "FEMALE", "GENERAL USE"]), {:prompt => "Select Type"}, {class: "form-control #{'is-invalid' if invalid_eligibility}"} %>
          <% else %>
            <%= form.select :eligibility, options_for_select(["MALE", "FEMALE", "GENERAL USE"],:selected => relief_good.eligibility.to_s), {:prompt => "Select Type"}, {class: "form-control #{'is-invalid' if invalid_eligibility}"} %>
          <%  end %>
          <% if invalid_eligibility %>
            <div class="invalid-feedback d-block">
              <% relief_good.errors[:eligibility].each do |error_message| %>
                <%= error_message %>.
              <% end %>
            </div>
          <% end %>
        </div>
        <div class="form-group m-2 p-1">
          <%= form.label :category, class: "h5 oswald fw text-uppercase" do %>
            Category(This will be assumed that the product can be use by chosen category and above): 
          <% end %>
          <% if relief_good.category == nil %>
            <%= form.select :category, options_for_select(["INFANTS","TODDLERS","PRE-SCHOOLERS","SCHOOLAGERS","TEENAGERS","ADULTS","SENIOR CITIZENS","ALL"]), {:prompt => "Select Category"}, {class: "form-control #{'is-invalid' if invalid_category}"} %>
          <% else %>
            <%= form.select :category, options_for_select(["INFANTS","TODDLERS","PRE-SCHOOLERS","SCHOOLAGERS","TEENAGERS","ADULTS","SENIOR CITIZENS","ALL"],:selected => relief_good.category.to_s), {:prompt => "Select Category"}, {class: "form-control #{'is-invalid' if invalid_category}"} %>
          <%  end %>
          <% if invalid_category %>
            <div class="invalid-feedback d-block">
              <% relief_good.errors[:category].each do |error_message| %>
                <%= error_message %>.
              <% end %>
            </div>
          <% end %>
        </div>
        <button class="btn btn-success text-light rounded-bottom p-2 w-100 text-decoration-none text-center mt-4">DONE</button>
      </div>
    </div>
  </div>
<% end %>

app/views/relief_goods/_relief_good.html.erb
<div id="<%= dom_id relief_good %>">
  <p>
    <strong>Name:</strong>
    <%= relief_good.name %>
  </p>

  <p>
    <strong>Is food:</strong>
    <%= relief_good.is_food %>
  </p>

  <p>
    <strong>Unit:</strong>
    <%= relief_good.unit %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= relief_good.price %>
  </p>

</div>

app/views/relief_goods/_search_results.html.erb
<table class="table table-striped table-hover border rounded">
  <thead>
    <tr>
      <th class="col">Name</th>
      <th class="col">Unit of MEASUREMENT</th>
      <th class="col">Cost per Unit(PHP)</th>
      <th class="col">Product is for</th>
      <th class="col">Category</th>
      <th class="col">Type</th>
      <th class="col-md-2">Actions</th>
    </tr>
  </thead>
  <tbody class="table-group-divider">
    <% relief_goods.each do |rg|%>
      <tr >
        <td><b><%= rg.name %></b></td>
        <td><%= rg.unit %></td>
        <td><%= rg.price %></td>
        <td><%= rg.eligibility %></td>
        <td><%= rg.category %></td>
        <% if rg.is_food == true%>
          <td>Food</td>
        <% else %>
          <td>Non-Food</td>
        <% end %>
        <td class="position-relative" >
          <%= link_to "/relief_goods/#{rg.id}/edit", class: "btn btn-dark form-control" do %>
            <i class="fa-regular fa-pen-to-square" style="color: #ffffff;"></i>&nbsp;Edit
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/relief_goods/edit.html.erb
<div class="row m-0">
  <div class="col-md-11 m-5 text-xs-center  mt-5">
    <div class="card" >
      <div class="card-body" >
        <div class="card-deck">
          <div id = "form_area">
            <%= render partial:"form", locals:{relief_good:@relief_good}%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/relief_goods/index.html.erb
<div class="row m-0 mt-5">
  <div class="col-md-11 m-5 text-xs-center  mt-5">
    <div class="card" >
      <div class="card-body" >
        <div class="card-deck">
          <div class="card shadow p-4">
            <div class="row">
              <div class="col-md-8" >
                <h1 class="oswald fw">RELIEF GOODS</h1>
              </div>
              <div class = "col-md-4">
                <a href = "/relief_goods/new" ><button style = "margin-top:5px;" class = "btn btn-primary bg-navy oswald fw-bold form-control"><i class="fa-solid fa-plus"></i> Add New Relief Good</button></a>
              </div>
            </div>
            <%= form_with url: "/relief_goods/search", method: :post do |form| %>
              <label for = "search_criteria"><strong>Search Criteria:</strong></label>
              <div class="input-group mb-3">
                <%= form.select :search_type, options_for_select(["NAME","UNIT"]),{},{class:"form-control"}%>
                <%= form.search_field :search_value , class: "form-control", placeholder: "Search a data here", oninput: "this.form.requestSubmit()" %>
              </div>
            <% end %>
            <div id = "relief_goods">
              <%= render partial: "search_results",locals:{relief_goods: @relief_goods}%>
            </div>
            <% if @relief_goods_count > 10 %>
              <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-left">
                  <li class="page-item ">
                    <% if @page  > 0 %>
                      <%= link_to "Previous Page", "/relief_goods?page=#{@page-1}", class:"page-link"%>
                    <% end %>
                  </li>
                  <li class="page-item">
                    <%= link_to "Next Page","/relief_goods?page=#{@page + 1}", class:"page-link"%>
                  </li>
                </ul>
              </nav>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/relief_goods/new.html.erb
<div class="row m-0">
  <div class="col-md-11 m-5 text-xs-center  mt-5">
    <div class="card" >
      <div class="card-body" >
        <div class="card-deck">
          <div id = "form_area">
            <%= render partial:"form", locals:{relief_good:@relief_good}%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/relief_goods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @relief_good %>

<div>
  <%= link_to "Edit this relief good", edit_relief_good_path(@relief_good) %> |
  <%= link_to "Back to relief goods", relief_goods_path %>

  <%= button_to "Destroy this relief good", @relief_good, method: :delete %>
</div>